import { describe, expect, test } from 'vitest';
import { encrypt } from '../../src/ciphers/m-94';

const possibleCiphertexts = [
    'KINGSANDQUEENSAAAAAAAAAAA',
    'ZJXJLGIXOXJWCMPQRSTUVWXYZ',
    'OKFHWPKAIYAOJFBJMDOTNVKJD',
    'LTYLEOPIVWLAIAVNYMJRKSWPN',
    'RLQKMCVHTITMLOHUOCYZHFRXB',
    'XMRMZIRPZCMNDDIBFNLXRDEMU',
    'SOTRVXOJEASFHWYTTEFQGLVVH',
    'PUVUXLGOFKXLBPKGHQXLOIDKY',
    'WVWOGUSBHEVHMKSIEBNYXETBF',
    'NYLQARYWGLQQKJGMUOGIEBUQW',
    'AGAVFNDKYBPGGVUWSZWOYHFWJ',
    'BZDPNDUCUDNCXIEZZPHVBKOUL',
    'CNKTQYLVNFOUUUNRJLVBFNYGV',
    'EPONUZCFLJHJZQTVXGCPSRHLG',
    'IQMWKHFZPGUTTHCLDVMEJJMOR',
    'GXJYDWMLMHWBSZXXPJISMQLSC',
    'DRUXOBQQBODYWCOCCRRNUZSTQ',
    'JWBZPJTEXNIPQTWSWKBHDGIEM',
    'FSGSISWRWMZZYXFHGYSJQMQCP',
    'VBEATQAYCTYKVBQDQTEWCXNHS',
    'UAPEJFHNRPCXOLDEIFKMLPJNO',
    'YCHDBKXSARGIREROBUUDZUCZE',
    'MDSCRVJUJQKSPGLKKIPGWCPFX',
    'HECBHMEMDSRRFNJFLWDFTOGRT',
    'THZICEZGSVFDEYZPNXZCITBIK',
    'QFIFYTBTKZBVARMYVHQKPYZDI',
];

describe('M-94 cipher - encryption', () => {
    test('Basic substitution', () => {
        expect(
            possibleCiphertexts.includes(encrypt('KINGS AND QUEENS')),
        ).toEqual(true);
    });
});
